spring:
  application:
    name: PFA

  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: pfa
      port: 27017
      host: localhost

